#!/bin/bash

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super Period focus-output previous
riverctl map normal Super Comma focus-output next

riverctl map normal Super+Shift Period send-to-output previous
riverctl map normal Super+Shift Comma send-to-output next

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super+Shift Return zoom
riverctl map normal Super+Shift Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Return spawn alacritty
riverctl map normal Super B spawn firefox
riverctl map normal Super D spawn 'wofi --insensitive --show drun'

riverctl map normal None XF86AudioRaiseVolume spawn 'pamixer -i 3'
riverctl map normal None XF86AudioLowerVolume spawn 'pamixer -d 3'
riverctl map locked None XF86AudioRaiseVolume spawn 'pamixer -i 3'
riverctl map locked None XF86AudioLowerVolume spawn 'pamixer -d 3'
riverctl map normal None XF86AudioMute spawn 'pamixer --toggle-mute'

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
	tags=$((1 << ($i-1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
done

riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl border-color-focused 0xaa0000

riverctl input "5426:110:Razer_Razer_DeathAdder_Essential" pointer-accel -0.2
riverctl input "5426:110:Razer_Razer_DeathAdder_Essential" accel-profile flat

wlr-randr --output DP-3 --mode 1920x1080 --pos 0,0 --output HDMI-A-1 --mode 1920x1080 pos 1920,0 --output DVI-I-1 --mode 1920x1080 --pos 3840,0

riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2
#riverctl default-layout stacktile
#stacktile --inner-padding 4 --outer-padding 4 --per-tag-config
