# # Remember to source this file in your hyprland.conf
$background = rgba(303446FF)
$foreground = rgba(C6D0F5FF)
$black = rgba(232634FF)
$red = rgba(E78284FF)
$green = rgba(A6D189FF)
$yellow = rgba(EF9F76FF)
$blue = rgba(8CAAEEFF)
$magenta = rgba(CA9EE6FF)
$cyan = rgba(85C1DCFF)
$white = rgba(B5BFE2FF)
$bblack = rgba(838BA7FF)
$bred = rgba(EA999CFF)
$bgreen = rgba(81C8BEFF)
$byellow = rgba(E5C890FF)
$bblue = rgba(85C1DCFF)
$bmagenta = rgba(F4B8E4FF)
$bcyan = rgba(99D1DBFF)
$bwhite = rgba(C6D0F5FF)