preload = /home/czarek/Pictures/.wp/dark/rose_pine_noiseline.png
wallpaper = DP-1, /home/czarek/Pictures/.wp/dark/rose_pine_noiseline.png
wallpaper = DP-2, /home/czarek/Pictures/.wp/dark/rose_pine_noiseline.png
wallpaper = HDMI-A-1, /home/czarek/Pictures/.wp/dark/rose_pine_noiseline.png
