## Remember to source this file in your hyprland.conf
$background = rgba(303446FF)
$foreground = rgba(C6D0F5FF)
$black = rgba(51576DFF)
$red = rgba(E78284FF)
$green = rgba(A6D189FF)
$yellow = rgba(E5C890FF)
$blue = rgba(8CAAEEFF)
$magenta = rgba(F4B8E4FF)
$cyan = rgba(81C8BEFF)
$white = rgba(B5BFE2FF)
$bblack = rgba(626880FF)
$bred = rgba(E78284FF)
$bgreen = rgba(A6D189FF)
$byellow = rgba(E5C890FF)
$bblue = rgba(8CAAEEFF)
$bmagenta = rgba(F4B8E4FF)
$bcyan = rgba(81C8BEFF)
$bwhite = rgba(A5ADCEFF)