# Start picom with experimental-backends
backend = "glx";
corner-radius = 8;
shadow = false;
inactive-opacity = 0.95;
active-opacity = 1;
blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 18;
fading = true;

rounded-corners-exclude = [
	"class_g = 'dwm'"
];

opacity-rule = [
	"80:class_g = 'Sakura'",
	"80:class_g = 'st'",
	"80:class_g = 'Alacritty'"
];
