# Start picom with experimental-backends
backend = "glx";
corner-radius = 8;
detect-rounded-corners = false;
unredir-if-possible = true;
glx-no-stencil = true;

# Opacity
inactive-opacity = 0.90;
active-opacity = 1;
frame-opacity = 0.75;

# Blur
blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 18;

# Fading
fading = true;
fade-in-step = 0.40;
fade-out-step = 0.40;
fade-delta = 24;

# Shadows
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.75;
shadow-color = "#000000";

# Excludes
rounded-corners-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dwmsystray'",
	"class_g = 'maim'",
];

opacity-rule = [
	"80:class_g = 'Sakura'",
	"80:class_g = 'st'",
	"100:class_g = 'Alacritty'",
];

shadow-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dwmsystray'",
	"class_g = 'maim'",
];
