[general]
import = [
	"theme.toml"
]

[window]
padding = { x = 4, y = 4 }
opacity = 0.95

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
